spring.application.name=URLEncoder
spring.data.mongodb.database=urlencoder
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.auto-index-creation=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG

app.jwt.keystore-location=file:C:/Users/ChandraVadhanReddySu/project1/URL-Encoder/backend/.secrets/jwt-keystore.p12
app.jwt.keystore-password=${JWT_KEYSTORE_PASSWORD:changeit}
app.jwt.private-key-password=${JWT_PRIVATE_KEY_PASSWORD:changeit}
app.jwt.key-alias=jwt-key

app.jwt.issuer=url-encoder-api
app.jwt.access-token-expiration=15m